# Generated by Django 3.2.4 on 2024-05-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0002_auto_20240526_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstation',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='busstation',
            name='id',
        ),
        migrations.AddField(
            model_name='bus',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='max_passenger_amount',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='speed',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='busstation',
            name='bus_station_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='passenger_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OnBusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_routing.bus')),
                ('end_bus_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_bus_station_set', to='bus_routing.busstation')),
                ('start_bus_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_bus_station_set', to='bus_routing.busstation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_routing.user')),
            ],
        ),
        migrations.CreateModel(
            name='BusRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_routing.busstation')),
            ],
        ),
    ]
