# Generated by Django 3.2.4 on 2024-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0003_auto_20240528_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='bus_station_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
