# Generated by Django 3.2.4 on 2024-05-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0004_alter_busstation_bus_station_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='passenger_amount',
            new_name='current_passenger_amount',
        ),
        migrations.RemoveField(
            model_name='busrouting',
            name='bus_number',
        ),
        migrations.AddField(
            model_name='busrouting',
            name='bus_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus_routing.bus'),
            preserve_default=False,
        ),
    ]
