# Generated by Django 3.2.4 on 2024-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0005_auto_20240528_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='bus_station_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
