# Generated by Django 3.2.4 on 2024-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0006_alter_busstation_bus_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onbusdata',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='onbusdata',
            name='bus_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onbusdata',
            name='end_bus_station_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onbusdata',
            name='start_bus_station_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onbusdata',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
