# Generated by Django 3.2.4 on 2024-06-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0008_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='bus_id',
            new_name='bus_number',
        ),
    ]
