# Generated by Django 3.2.4 on 2024-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0009_rename_bus_id_ticket_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus_number',
            field=models.CharField(max_length=255),
        ),
    ]
