# Generated by Django 5.0.4 on 2024-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0011_movementhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='off_bus_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='on_bus_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='bus_id',
            field=models.IntegerField(null=True),
        ),
    ]
