# Generated by Django 5.0.4 on 2024-06-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0012_remove_movementhistory_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onbusdata',
            old_name='bus_id',
            new_name='tiket_id',
        ),
        migrations.RemoveField(
            model_name='onbusdata',
            name='user_id',
        ),
    ]
