# Generated by Django 5.0.4 on 2024-06-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0013_rename_bus_id_onbusdata_tiket_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onbusdata',
            old_name='tiket_id',
            new_name='ticket_id',
        ),
    ]
