# Generated by Django 5.0.4 on 2024-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0014_rename_tiket_id_onbusdata_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementhistory',
            name='off_bus_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movementhistory',
            name='on_bus_at',
            field=models.DateTimeField(null=True),
        ),
    ]
