# Generated by Django 5.0.4 on 2024-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0015_alter_movementhistory_off_bus_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementhistory',
            name='ticket_id',
            field=models.IntegerField(null=True),
        ),
    ]
