# Generated by Django 5.0.4 on 2024-06-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0016_movementhistory_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('bus_number', models.CharField(max_length=255)),
                ('on_bus_station_id', models.IntegerField()),
                ('off_bus_station_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
