# Generated by Django 5.0.4 on 2024-06-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0017_ticketstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busrouting',
            name='bus_id',
        ),
        migrations.RemoveField(
            model_name='busrouting',
            name='bus_station',
        ),
        migrations.AddField(
            model_name='busrouting',
            name='bus_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='busrouting',
            name='bus_station_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busstation',
            name='bus_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
