# Generated by Django 5.0.4 on 2024-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0018_remove_busrouting_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='direction',
            field=models.IntegerField(default=0),
        ),
    ]
