# Generated by Django 5.0.4 on 2024-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0019_busstation_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='current_position',
        ),
        migrations.AddField(
            model_name='bus',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
