# Generated by Django 5.0.4 on 2024-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0020_remove_bus_current_position_bus_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='bus_number_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
