# Generated by Django 5.0.4 on 2024-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0021_busstation_bus_number_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstation',
            old_name='bus_number_list',
            new_name='bus_number_list_go',
        ),
        migrations.AddField(
            model_name='busstation',
            name='bus_number_list_return',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
