# Generated by Django 5.0.4 on 2024-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0023_bus_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busrouting',
            old_name='bus_station_id',
            new_name='direction',
        ),
        migrations.AddField(
            model_name='busrouting',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
