# Generated by Django 5.0.4 on 2024-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0025_busstation_bus_number_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_number_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
