# Generated by Django 5.0.4 on 2024-07-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0026_bus_bus_number_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovementHistory',
        ),
        migrations.DeleteModel(
            name='TicketStation',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='bus_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bus_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
