# Generated by Django 5.0.4 on 2024-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0027_delete_movementhistory_delete_ticketstation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
