# Generated by Django 5.0.4 on 2024-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0028_busstation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstation',
            name='polyline_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
