# Generated by Django 5.0.4 on 2024-07-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0031_onbuspassengerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='người dùng', max_length=255),
            preserve_default=False,
        ),
    ]
