# Generated by Django 5.0.4 on 2024-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0033_buspassengerdata_checktickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktickethistory',
            name='driver_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
