# Generated by Django 5.0.4 on 2024-07-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_routing', '0035_buspassengerdata_dirver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buspassengerdata',
            old_name='dirver_name',
            new_name='driver_name',
        ),
    ]
